/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

//=================================================================================================
#include "driver_init.h"
#include <system.h>
#include <main.h>

//=================================================================================================
void I2C_0_initialization(void)
{

	PF3_set_level(
	// <y> Initial level
	// <id> pad_initial_level
	// <false"> Low
	// <true"> High
	false);

	PF3_set_dir(
	// <y> Pin direction
	// <id> pad_dir
	// <PORT_DIR_OFF"> Off
	// <PORT_DIR_IN"> In
	// <PORT_DIR_OUT"> Out
	PORT_DIR_OUT);

	PF3_set_pull_mode(
	// <y> Pull configuration
	// <id> pad_pull_config
	// <PORT_PULL_OFF"> Off
	// <PORT_PULL_UP"> Pull-up
	PORT_PULL_OFF);

	PF3_set_inverted(
	// <y> Invert I/O on pin
	// <id> pad_invert
	// <false"> Not inverted
	// <true"> Inverted
	false);

	PF3_set_isc(
	// <y> Pin Input/Sense Configuration
	// <id> pad_isc
	// <PORT_ISC_INTDISABLE_gc"> Interrupt disabled but input buffer enabled
	// <PORT_ISC_BOTHEDGES_gc"> Sense Both Edges
	// <PORT_ISC_RISING_gc"> Sense Rising Edge
	// <PORT_ISC_FALLING_gc"> Sense Falling Edge
	// <PORT_ISC_INPUT_DISABLE_gc"> Digital Input Buffer disabled
	// <PORT_ISC_LEVEL_gc"> Sense low Level
	PORT_ISC_INTDISABLE_gc);

	PF2_set_level(
	// <y> Initial level
	// <id> pad_initial_level
	// <false"> Low
	// <true"> High
	false);

	PF2_set_dir(
	// <y> Pin direction
	// <id> pad_dir
	// <PORT_DIR_OFF"> Off
	// <PORT_DIR_IN"> In
	// <PORT_DIR_OUT"> Out
	PORT_DIR_OUT);

	PF2_set_pull_mode(
	// <y> Pull configuration
	// <id> pad_pull_config
	// <PORT_PULL_OFF"> Off
	// <PORT_PULL_UP"> Pull-up
	PORT_PULL_OFF);

	PF2_set_inverted(
	// <y> Invert I/O on pin
	// <id> pad_invert
	// <false"> Not inverted
	// <true"> Inverted
	false);

	PF2_set_isc(
	// <y> Pin Input/Sense Configuration
	// <id> pad_isc
	// <PORT_ISC_INTDISABLE_gc"> Interrupt disabled but input buffer enabled
	// <PORT_ISC_BOTHEDGES_gc"> Sense Both Edges
	// <PORT_ISC_RISING_gc"> Sense Rising Edge
	// <PORT_ISC_FALLING_gc"> Sense Falling Edge
	// <PORT_ISC_INPUT_DISABLE_gc"> Digital Input Buffer disabled
	// <PORT_ISC_LEVEL_gc"> Sense low Level
	PORT_ISC_INTDISABLE_gc);

	I2C_0_init();
}

//=================================================================================================
#ifdef Usart_0
void USART_0_initialization(void)			// USART 0 의 핀을 설정하고 레지스터를 초기화
{
	#if Usart_0 == 0
	PORTMUX.USARTROUTEA &= ~PORTMUX_USART00_bm;	// USART 0 송,수신 : Pin PC4, PC5 로 변경
	PORTA.DIR |=  PIN0_bm;				// set pin 4 of	PORT A (TXd) as	output (PORT A (TXd)의 4번 핀을 출력으로 설정)
	PORTA.DIR &= ~PIN1_bm;				// set pin 5 of	PORT A (RXd) as	input  (PORT A (RXd)의 5번 핀을 입력으로 설정)
	#elif Usart_0 == 1
	PORTMUX.USARTROUTEA |= PORTMUX_USART00_bm;	// USART 0 송,수신 : Pin PC4, PC5 로 변경
	PORTA.DIR |=  PIN4_bm;				// set pin 4 of	PORT A (TXd) as	output (PORT A (TXd)의 4번 핀을 출력으로 설정)
	PORTA.DIR &= ~PIN5_bm;				// set pin 5 of	PORT A (RXd) as	input  (PORT A (RXd)의 5번 핀을 입력으로 설정)
	#endif
	USART_0_init();
}
#endif

//=================================================================================================
#ifdef Usart_1
void USART_1_initialization(void)			// USART 1 의 핀을 설정하고 레지스터를 초기화
{
	#if Usart_1 == 0
	PORTMUX.USARTROUTEA &= ~PORTMUX_USART10_bm;	// USART 1 송,수신 : Pin PC0, PC1 로 변경
	PORTC.DIR |=  PIN0_bm;				// set pin 0 of	PORT C (TXd) as	output (PORT C (TXd)의 0번 핀을 출력으로 설정)
	PORTC.DIR &= ~PIN1_bm;				// set pin 1 of	PORT C (RXd) as	input  (PORT C (RXd)의 1번 핀을 입력으로 설정)
	#elif Usart_1 == 1
	PORTMUX.USARTROUTEA |= PORTMUX_USART10_bm;	// USART 1 송,수신 : Pin PC4, PC5 로 변경
	PORTC.DIR |=  PIN4_bm;				// set pin 4 of	PORT C (TXd) as	output (PORT C (TXd)의 4번 핀을 출력으로 설정)
	PORTC.DIR &= ~PIN5_bm;				// set pin 5 of	PORT C (RXd) as	input  (PORT C (RXd)의 5번 핀을 입력으로 설정)
	#endif
	USART_1_init();
}
#endif

//=================================================================================================
#ifdef Usart_2
void USART_2_initialization(void)			// USART 2 의 핀을 설정하고 레지스터를 초기화
{
	#if Usart_2 == 0
	PORTMUX.USARTROUTEA &= ~PORTMUX_USART20_bm;	// USART 2 송,수신 : Pin PF4, PF5 로 변경
	PORTF.DIR |=  PIN0_bm;				// set pin 0 of	PORT F (TXd) as	output (PORT F (TXd)의 0번 핀을 출력으로 설정)
	PORTF.DIR &= ~PIN1_bm;				// set pin 1 of	PORT F (RXd) as	input  (PORT F (RXd)의 1번 핀을 입력으로 설정)
	#elif Usart_2 == 1
	PORTMUX.USARTROUTEA |= PORTMUX_USART20_bm;	// USART 2 송,수신 : Pin PF4, PF5 로 변경
	PORTF.DIR |=  PIN4_bm;				// set pin 4 of	PORT F (TXd) as	output (PORT F (TXd)의 4번 핀을 출력으로 설정)
	PORTF.DIR &= ~PIN5_bm;				// set pin 5 of	PORT F (RXd) as	input  (PORT F (RXd)의 5번 핀을 입력으로 설정)
	#endif
	USART_2_init();
}
#endif

//=================================================================================================
#ifdef Usart_3
void USART_3_initialization(void)			// USART 3 의 핀을 설정하고 레지스터를 초기화
{
	#if Usart_3 == 0
	PORTMUX.USARTROUTEA &= ~PORTMUX_USART30_bm;	// USART 3 송,수신 : Pin PB0, PB1 로 변경
	PORTB.DIR |=  PIN0_bm;				// set pin 0 of	PORT B (TXd) as	output (PORT B (TXd)의 0번 핀을 출력으로 설정)
	PORTB.DIR &= ~PIN1_bm;				// set pin 1 of	PORT B (RXd) as	input  (PORT B (RXd)의 1번 핀을 입력으로 설정)
	#elif Usart_3 == 1
	PORTMUX.USARTROUTEA |= PORTMUX_USART30_bm;	// USART 3 송,수신 : Pin PB4, PB5 로 변경
	PORTB.DIR |=  PIN4_bm;				// set pin 4 of	PORT B (TXd) as output (PORT B (TXd)의 4번 핀을 출력으로 설정)
	PORTB.DIR &= ~PIN5_bm;				// set pin 5 of	PORT B (RXd) as input  (PORT B (RXd)의 5번 핀을 입력으로 설정)
	#endif
	USART_3_init();
}
#endif

//=================================================================================================
#ifdef Usart_4
void USART_4_initialization(void)			// USART 4 의 핀을 설정하고 레지스터를 초기화
{
	#if Usart_4 == 0
	PORTMUX.USARTROUTEB &= ~PORTMUX_USART40_bm;	// USART 4 송,수신 : Pin PE0, PE1 로 변경
	PORTE.DIR |=  PIN0_bm;				// set pin 0 of	PORT E (TXd) as	output (PORT E (TXd)의 0번 핀을 출력으로 설정)
	PORTE.DIR &= ~PIN1_bm;				// set pin 1 of	PORT E (RXd) as	input  (PORT E (RXd)의 1번 핀을 입력으로 설정)
	#elif Usart_4 == 1
	PORTMUX.USARTROUTEB |= PORTMUX_USART40_bm;	// USART 4 송,수신 : Pin PE4, PE5 로 변경
	PORTE.DIR |=  PIN4_bm;				// set pin 4 of	PORT E (TXd) as output (PORT E (TXd)의 4번 핀을 출력으로 설정)
	PORTE.DIR &= ~PIN5_bm;				// set pin 5 of	PORT E (RXd) as input  (PORT E (RXd)의 5번 핀을 입력으로 설정)
	#endif
	USART_4_init();
}
#endif

//=================================================================================================
#ifdef Usart_5
void USART_5_initialization(void)			// USART 5 의 핀을 설정하고 레지스터를 초기화
{
	#if Usart_5 == 0
	PORTMUX.USARTROUTEB &= ~PORTMUX_USART50_bm;	// USART 5 송,수신 : Pin PG4, PG5 로 변경
	PORTG.DIR |=  PIN0_bm;				// set pin 0 of	PORT G (TXd) as	output (PORT G (TXd)의 0번 핀을 출력으로 설정)
	PORTG.DIR &= ~PIN1_bm;				// set pin 1 of	PORT G (RXd) as	input  (PORT G (RXd)의 1번 핀을 입력으로 설정)
	#elif Usart_5 == 1
	PORTMUX.USARTROUTEB |= PORTMUX_USART50_bm;	// USART 5 송,수신 : Pin PG4, PG5 로 변경
	PORTG.DIR |=  PIN4_bm;				// set pin 4 of	PORT G (TXd) as output (PORT G (TXd)의 4번 핀을 출력으로 설정)
	PORTG.DIR &= ~PIN5_bm;				// set pin 5 of	PORT G (RXd) as input  (PORT G (RXd)의 5번 핀을 입력으로 설정)
	#endif
	USART_5_init();
}
#endif

//=================================================================================================
#ifdef ADC_SET
void ADC_initialization(void)
{
	ADC0.MUXPOS = ADC_MUXPOS_AIN0_gc;		// ADC input pin 0

	/* Disable interrupt and digital input buffer on PD0 */
	PORTD.PIN0CTRL &= ~PORT_ISC_gm;
	PORTD.PIN0CTRL |= PORT_ISC_INPUT_DISABLE_gc;

	/* Disable pull-up resistor */
	PORTD.PIN0CTRL &= ~PORT_PULLUPEN_bm;
	
	ADC_init();
}
#endif

//=================================================================================================
#ifdef DAC_SET
void DAC_initialization(void)
{
	// Disable digital input buffer
	PD6_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	PD6_set_pull_mode(PORT_PULL_OFF);

	DAC_init();
}
#endif

//=================================================================================================
#ifdef PWM_SET
void PWM_0_initialization(void)
{
	// Set pin direction to output

	PWM_set_level(false);
	// <y> Initial level
	// <id> pad_initial_level
	// <false"> Low
	// <true"> High

	PWM_set_dir(PORT_DIR_OUT);

	/* set the alternate pin mux */

	PORTMUX.TCAROUTEA |= PORTMUX_TCA01_bm;

	PWM_0_init();
}
#endif

//=================================================================================================
void system_init()
{
	mcu_init();
//-------------------------------------------------------------------------------------------------
	CLKCTRL_init();
//-------------------------------------------------------------------------------------------------
#ifdef Usart_0
	USART_0_initialization();			// USART 0 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef Usart_1
	USART_1_initialization();			// USART 1 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef Usart_2
	USART_2_initialization();			// USART 2 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef Usart_3
 	USART_3_initialization();			// USART 3 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef Usart_4
 	USART_4_initialization();			// USART 4 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef Usart_5
 	USART_5_initialization();			// USART 5 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef ADC_SET
	ADC_initialization();				// ACD 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef DAC_SET
	DAC_initialization();				// DAC를 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
#ifdef PWM_SET
	PWM_0_initialization();					// PWM0 의 핀을 설정하고 레지스터를 초기화
#endif
//-------------------------------------------------------------------------------------------------
	SLPCTRL_init();
//-------------------------------------------------------------------------------------------------
#ifdef Timer_0
	TIMER_0_init();
#endif
//-------------------------------------------------------------------------------------------------
#ifdef Timer_1
	TIMER_1_init();
#endif
//-------------------------------------------------------------------------------------------------
	BOD_init();
//-------------------------------------------------------------------------------------------------
	WDT_init();
//-------------------------------------------------------------------------------------------------
	I2C_0_initialization();
//-------------------------------------------------------------------------------------------------
}

//=================================================================================================
