/**
 * \file
 *
 * \brief Driver ISR.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

//=================================================================================================
#include <main.h>
#include <driver_init.h>
#include <compiler.h>

//=================================================================================================
void Beep(uint16_t BeepTimer_1ms)
{
	Buzzer_ON;								// Buzzer on
	Beep_Timer = BeepTimer_1ms;
}

//=================================================================================================
#ifdef Usart_0
ISR(USART0_RXC_vect)
{
	while(!(USART0.STATUS & USART_RXCIF_bm)) ;
	Rx0_Buff[Rx0_Cnt] = USART0.RXDATAL;
	if(Rx0_Cnt >= RX0_SIZE) {Rx0_Cnt = 0;}					// RX0_SIZE : 250
	Rx0_Cnt++;
}
#endif

//=================================================================================================
#ifdef Usart_1
ISR(USART1_RXC_vect)
{
	while(!(USART1.STATUS & USART_RXCIF_bm)) ;
	Rx1_Buff[Rx1_Cnt] = USART1.RXDATAL;
	if(Rx1_Cnt >= RX1_SIZE) {Rx1_Cnt = 0;}					// RX1_SIZE : 250
	Rx1_Cnt++;
}
#endif

//=================================================================================================
#ifdef Usart_2
ISR(USART2_RXC_vect)
{
	while(!(USART2.STATUS & USART_RXCIF_bm)) ;
	Rx2_Buff[Rx2_Cnt] = USART2.RXDATAL;
	if(Rx2_Cnt >= RX2_SIZE) {Rx2_Cnt = 0;}					// RX2_SIZE : 250
	Rx2_Cnt++;
}
#endif

//=================================================================================================
#ifdef Usart_3
ISR(USART3_RXC_vect)
{
	while(!(USART3.STATUS & USART_RXCIF_bm)) ;
	Rx3_Buff[Rx3_Cnt] = USART3.RXDATAL;
	if(Rx3_Cnt >= RX3_SIZE) {Rx3_Cnt = 0;}					// RX3_SIZE : 250
	Rx3_Cnt++;
}
#endif

//=================================================================================================
#ifdef Usart_4
ISR(USART4_RXC_vect)
{
	while(!(USART4.STATUS & USART_RXCIF_bm)) ;
	Rx4_Buff[Rx4_Cnt] = USART4.RXDATAL;
	if(Rx4_Cnt >= RX4_SIZE) {Rx4_Cnt = 0;}					// RX4_SIZE : 250
	Rx4_Cnt++;
}
#endif

//=================================================================================================
#ifdef Usart_5
ISR(USART5_RXC_vect)
{
	while(!(USART5.STATUS & USART_RXCIF_bm)) ;
	Rx5_Buff[Rx5_Cnt] = USART5.RXDATAL;
	if(Rx5_Cnt >= RX5_SIZE) {Rx5_Cnt = 0;}					// RX5_SIZE : 250
	Rx5_Cnt++;
}
#endif

//=================================================================================================
#ifdef Timer_0
ISR(TCA0_OVF_vect)								// 500mSec Timer
{
	TCA0.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;				// TCA0 오버플로워 SET
}
#endif

//=================================================================================================
#ifdef Timer_1
ISR(TCA1_OVF_vect)								// 5mSec Timer
{
	TCA1.SINGLE.INTFLAGS = TCA_SINGLE_OVF_bm;				// TCA1 오버플로워 SET

 	Fnd_Display();								// FND Display
	Key_Scan();								// key 입력 체크

	if(Timer.Input_Key == 0) {KEY.Buff = 0; KEY.Key = 0;}			// Timer.Input_Key 가 0 이면 Key 값 및 Key 입력 초기화
	else			 {Timer.Input_Key--;}				// Timer.Input_Key 가 0 이 아니면 Timer.Input_Key 감소
//-------------------------------------------------------------------------------------------------
	if(Beep_Timer == 0) {Buzzer_OFF;}					// Beep_Timer 가 0 이면 Buzzer OFF
	else		    {Beep_Timer--;}					// Beep_Timer 가 0 이 아니면 Beep_Timer 감소
//-------------------------------------------------------------------------------------------------
	Timer.RegExitTimer++;							// Timer.RegExitTimer 증가 (5mSec 마다)
	if(Timer.RegExitTimer >= REG_EXIT_TIME)					// Timer.RegExitTimer 가 REG_EXIT_TIME 과 같거나 크면
	{									// 설정 모드후 일정시간(10초) 버튼 입력 없으면 탈출
		SET.Menu = 0;							// Menu 모드 초기화
		SET.Select = 0;							// Select 모드 초기화
	}
//-------------------------------------------------------------------------------------------------
// 	if(!Auto_Mode)
// 	{
// 		Timer.FndExitTimer++;						// Timer.FndExitTimer 감소 (5mSec 마다)
// 		if(Timer.FndExitTimer > FND_EXIT_TIME)				// Timer.FndExitTimer 가 FND_EXIT_TIME 보다 크면 Slip 모드 ON (FND ALL OFF)
// 		{
// 			SET.Slip = 1;
// 			Timer.FndExitTimer = FND_EXIT_TIME;
// 		}
// 		else                                                            // 아니면 FND Display
// 		{
// 			SET.Slip = 0;
// 		}
// 	}
//-------------------------------------------------------------------------------------------------
 	Timer.RTC_Timer++;							// Timer.RTC_Timer 증가 (5mSec 마다)
//  	Timer.Limit_Timer++;							// 무게측정 제한 시간 증가 (5mSec 마다)
//-------------------------------------------------------------------------------------------------
	Blink_Timer++;								// Blink_Timer 증가 (5mSec 마다)
	if(Blink_Timer > 50)							// Blink_Timer 이 50(0.25초)보다 크면
	{
		Blink = Blink ? 0 : 1;						// Blink 이 1이면 0으로 0이면 1로 변경
		Blink_Timer = 0;						// Blink_Timer 초기화
	}
//-------------------------------------------------------------------------------------------------
}
#endif

//=================================================================================================
